version: "3.7"
services:
  wordpress:
      container_name : wordpress
      build:
        ./requirements/wordpress/.
      ports:
        - "9000:9000"
      restart: on-failure
      env_file:
        - .env
      volumes:
        - wp:/var/www/html
      networks:
        - inception
      depends_on:
        - mariadb
  nginx:
      container_name : nginx
      build:
        ./requirements/nginx/.
      env_file:
        - .env
      ports:
        - 443:443
        - 80:80
      restart: on-failure
      volumes:
        - wp:/var/www/html
      networks:
        - inception
      depends_on:
        - wordpress
  mariadb:
      container_name : mariadb
      build:
        ./requirements/mariadb/.
      networks:
        - inception
      volumes:
        - mdb:/var/lib/mysql
      restart: always
      env_file:
        - .env
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - inception
volumes:
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/aait-oma/Desktop/inception/data/wp
  mdb:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: /Users/aait-oma/Desktop/inception/data/mdb

networks:
  inception:
    driver: bridge
